Idna dependency
projectdiscovery/fastdialer pull request #36
Opened 2022-05-12 19:52 UTC by LuitelSamikshya

2022-05-13 07:19 UTC, Mzack9999 requested changes

2022-05-13 07:19 UTC, Mzack9999 commented on fastdialer/dialer.go
> +		hostnameAscii, err := idna.New().ToASCII(hostname)
I think this can be replaced with:
```go
hostnameAscii, err := idna.ToASCII(hostname)
```

2022-05-13 20:48 UTC, LuitelSamikshya commented on fastdialer/dialer.go
> +		hostnameAscii, err := idna.New().ToASCII(hostname)
Done

2022-05-15 10:59 UTC, Mzack9999 approved these changes

2022-05-15 11:01 UTC, merged